name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - php-version: "7.1"
            dependencies: "highest"
          - php-version: "7.2"
            dependencies: "locked"
          - php-version: "7.3"
            dependencies: "locked"
          - php-version: "7.4"
            dependencies: "locked"
          - php-version: "8.0"
            dependencies: "locked"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-version }}

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: 'echo "::set-output name=directory::$(composer config cache-dir)"'

      - name: "Composer install"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Run tests"
        run: "php vendor/bin/captainhook hook:pre-commit"
